### PR TITLE
README.rst: Syntax highlight patrol.py

### PR DESCRIPTION
**Pull request by msabramo**

### CODE REVIEW

**Comment by crdoconnor** [comment]
Can you somehow re-issue these pull requests? I think I might have rendered it unmergeable when I overwrote my email address on the first two commits from last night.

**Comment by crdoconnor** [comment]
Added manually. Thanks for the tip!

**Comment by msabramo** [comment]
Ah I see you did this manually. Need me to reissue anything else?

**Comment by crdoconnor** [comment]
If you see anything else that you think needs changing or fixing, sure.

**Pull request closed without merging**
